name: cloudchain
description: IPFS cloud storage system.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12

  pinata: ^0.0.1+5
  preset: ^0.0.1+94
  qp_xt_flutter: ^0.0.2+4
  text2: ^0.0.1+1
  mat3d: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
